package fingerprint

// libraryRulesApp 是"应用层"扩展规则：Web 服务器/中间件、Java 生态、语言框架、
// CMS、数据库与面板、DevOps/CI/制品、大数据与搜索、监控与日志、代理网关缓存、
// 文件协作与 Web 邮件。
//
// 维护要求见 rules_library.go 顶部注释；每条规则都要在 rules_library_app_test.go
// 里有对应的正样本，否则视为"死规则"。
//
// 写规则时的额外注意（本项目踩过的坑）：
//   - 只用 RE2 语法，禁止 lookahead/lookbehind/反向引用；
//   - 禁止裸 `.*`，header 值正则一律用 `.+`；
//   - 每条规则必须带具体字面量（产品名/独特路径/独特 JSON 键），不能只靠 \d+；
//   - 能用 Ports 收敛的一定写 Ports；
//   - 不写 favicon_hash（无法离线校验 mmh3，写错就是永久漏报）；
//   - 变体产品用明确后缀（Tomcat 9 / Nginx Unit / Tengine），不与内置 48 条同名。
func libraryRulesApp() []Rule {
	out := make([]Rule, 0, 120)

	// ---------------- Web 服务器 / 中间件 ----------------
	out = append(out,
		Rule{Name: "Tomcat 9", Service: "http",
			Body: []string{`(?i)apache tomcat/9\.`, `(?i)tomcat/9\.\d`}},
		Rule{Name: "Tomcat 10", Service: "http",
			Body: []string{`(?i)apache tomcat/10\.`, `(?i)tomcat/10\.\d`}},
		Rule{Name: "Tomcat 8", Service: "http",
			Body: []string{`(?i)apache tomcat/8\.`, `(?i)tomcat/8\.\d`}},
		Rule{Name: "Jetty", Service: "http",
			Header: map[string]string{"server": `(?i)jetty(\(|/|\s|$)`}},
		Rule{Name: "WildFly", Service: "http",
			Header: map[string]string{"server": `(?i)wildfly`},
			Title:  []string{`(?i)wildfly`},
			Body:   []string{`(?i)wildfly`, `(?i)jboss\.as\.management`}},
		Rule{Name: "JBoss", Service: "http",
			Header: map[string]string{"server": `(?i)jboss`},
			Body:   []string{`(?i)jboss\.web`, `(?i)jboss-eap`}},
		Rule{Name: "WebSphere", Service: "http",
			Body:  []string{`(?i)websphere`, `(?i)ibm-websphere`},
			Title: []string{`(?i)websphere`}},
		Rule{Name: "GlassFish", Service: "http",
			Header: map[string]string{"server": `(?i)glassfish`},
			Title:  []string{`(?i)glassfish`},
			Body:   []string{`(?i)glassfish`}},
		Rule{Name: "Resin", Service: "http",
			Header: map[string]string{"server": `(?i)resin`},
			Body:   []string{`(?i)resin`}},
		Rule{Name: "Undertow", Service: "http",
			Header: map[string]string{"server": `(?i)undertow`}},
		Rule{Name: "Caddy", Service: "http",
			Header: map[string]string{"server": `(?i)caddy`}},
		Rule{Name: "Lighttpd", Service: "http",
			Header: map[string]string{"server": `(?i)lighttpd`}},
		Rule{Name: "Microsoft IIS 6.0", Service: "http",
			Header: map[string]string{"server": `(?i)microsoft-iis/6\.`}},
		Rule{Name: "Microsoft IIS 7.5", Service: "http",
			Header: map[string]string{"server": `(?i)microsoft-iis/7\.5`}},
		Rule{Name: "Microsoft IIS 10.0", Service: "http",
			Header: map[string]string{"server": `(?i)microsoft-iis/10\.`}},
		Rule{Name: "Tengine", Service: "http",
			Header: map[string]string{"server": `(?i)tengine`}},
		Rule{Name: "Nginx Unit", Service: "http",
			Header: map[string]string{"server": `(?i)unit/\d`},
			Body:   []string{`(?i)"unit"`}},
	)

	// ---------------- Java 生态 / 框架 ----------------
	out = append(out,
		Rule{Name: "Apache Shiro", Service: "http",
			Header: map[string]string{
				"set-cookie": `rememberMe=`,
				"x-shiro":    `.+`,
			},
			Title: []string{`(?i)shiro`},
			Body:  []string{`(?i)shiro`, `(?i)rememberMe`}},
		Rule{Name: "Apache Struts2", Service: "http",
			Body:  []string{`\.action["']`, `(?i)struts`},
			Title: []string{`(?i)struts`}},
		Rule{Name: "Spring Cloud Gateway", Service: "http",
			Body:  []string{`(?i)spring cloud gateway`},
			Title: []string{`(?i)spring cloud gateway`}},
		Rule{Name: "Spring Security", Service: "http",
			Title: []string{`(?i)spring security`},
			Body:  []string{`Please sign in`, `(?i)spring security`}},
		Rule{Name: "Fastjson", Service: "http",
			Body: []string{`(?i)fastjson`, `(?i)com\.alibaba\.fastjson`}},
		Rule{Name: "Druid Monitor", Service: "http",
			Title: []string{`(?i)druid`},
			Body:  []string{`(?i)druid`, `(?i)druid\.js`, `Druid Stat Index`}},
		Rule{Name: "Swagger UI", Service: "http",
			Title: []string{`(?i)swagger`},
			Body:  []string{`swagger-ui`, `(?i)Swagger UI`, `(?i)swagger-ui-bundle\.js`, `(?i)swagger-ui-standalone-preset`}},
		Rule{Name: "Apollo GraphQL", Service: "http",
			Body: []string{`GraphQL operations must contain`, `(?i)apollo-server`, `(?i)Apollo Server`}},
		Rule{Name: "GraphQL Playground", Service: "http",
			Title: []string{`(?i)graphql playground`},
			Body:  []string{`(?i)graphql-playground`, `"GraphQL Playground"`}},
		Rule{Name: "Spring Actuator", Service: "http",
			Body: []string{`"_links"\s*:\s*\{\s*"self"`, `"activeProfiles"\s*:`, `"propertySources"\s*:`}},
		Rule{Name: "Jenkins API", Service: "http",
			Header: map[string]string{"x-jenkins": `\d`, "x-jenkins-session": `.+`}},
	)

	// ---------------- 语言 / 框架 ----------------
	out = append(out,
		Rule{Name: "Django", Service: "http",
			Header: map[string]string{"set-cookie": `csrftoken=`},
			Title:  []string{`(?i)django`},
			Body:   []string{`CSRF verification failed`, `(?i)csrfmiddlewaretoken`, `(?i)django`}},
		Rule{Name: "Flask", Service: "http",
			Header: map[string]string{"server": `(?i)werkzeug`}},
		Rule{Name: "Express", Service: "http",
			Header: map[string]string{"x-powered-by": `(?i)express`}},
		Rule{Name: "NestJS", Service: "http",
			Header: map[string]string{"x-powered-by": `(?i)nestjs`},
			Body:   []string{`(?i)nestjs`}},
		Rule{Name: "Laravel", Service: "http",
			Header: map[string]string{"set-cookie": `(?i)laravel_session=`},
			Body:   []string{`(?i)laravel`}},
		Rule{Name: "Ruby on Rails", Service: "http",
			Header: map[string]string{"x-runtime": `\d`, "x-powered-by": `(?i)phusion passenger`, "set-cookie": `_rails_session|_session_id=`},
			Body:   []string{`(?i)ruby on rails`, `(?i)rails`}},
		Rule{Name: "Next.js", Service: "http",
			Header: map[string]string{"x-powered-by": `(?i)next\.js`},
			Body:   []string{`__NEXT_DATA__`, `/_next/static/`}},
		Rule{Name: "Nuxt", Service: "http",
			Header: map[string]string{"x-powered-by": `(?i)nuxt`},
			Body:   []string{`__NUXT__`, `/_nuxt/`}},
		Rule{Name: "Vue CLI", Service: "http",
			Title: []string{`(?i)vue cli`},
			Body:  []string{`(?i)vue-cli`, `@vue/cli`}},
		Rule{Name: "Vite Dev Server", Service: "http",
			Body:  []string{`@vite/client`, `/@vite/client`},
			Title: []string{`(?i)vite`}},
	)

	// ---------------- CMS / 建站 ----------------
	out = append(out,
		Rule{Name: "WordPress", Service: "http",
			Header: map[string]string{"x-pingback": `/xmlrpc\.php$`, "link": `wp-json`},
			Body:   []string{`wp-content/`, `wp-includes/`, `/wp-json/`, `(?i)wp-emoji-release\.min\.js`}},
		Rule{Name: "Drupal", Service: "http",
			Header: map[string]string{"x-generator": `(?i)drupal`},
			Body:   []string{`Drupal\.settings`, `(?i)drupal\.js`, `sites/default/files`}},
		Rule{Name: "Joomla", Service: "http",
			Body:  []string{`/media/jui/`, `(?i)Joomla!`, `/components/com_content/`},
			Title: []string{`(?i)joomla`}},
		Rule{Name: "Typecho", Service: "http",
			Body: []string{`(?i)typecho`, `/usr/themes/`, `/index.php/archives/`}},
		Rule{Name: "Discuz", Service: "http",
			Body: []string{`(?i)discuz`, `forum\.php\?mod=`, `(?i)static/image/common/`}},
		Rule{Name: "PHPCMS", Service: "http",
			Body: []string{`(?i)phpcms`, `/statics/js/`, `/index\.php\?m=content`}},
		Rule{Name: "DedeCMS", Service: "http",
			Body: []string{`(?i)dedecms`, `(?i)power by dedecms`, `/templets/default/`}},
		Rule{Name: "Ghost", Service: "http",
			Header: map[string]string{"x-powered-by": `(?i)ghost`},
			Body:   []string{`(?i)ghost`, `/assets/built/`, `content="Ghost`}},
		Rule{Name: "Halo", Service: "http",
			Body: []string{`(?i)halo`, `/api/content/`, `/themes/theme-`}},
		Rule{Name: "Hexo", Service: "http",
			Body: []string{`(?i)hexo`, `/js/hexo`, `hexo-generator`}},
	)

	// ---------------- 数据库及其 Web 面板 ----------------
	out = append(out,
		Rule{Name: "ClickHouse", Service: "http", Ports: []int{8123, 8443, 9000},
			Header: map[string]string{"x-clickhouse-server-display-name": `.+`, "x-clickhouse-query-id": `.+`},
			Body:   []string{`(?i)clickhouse`, `X-ClickHouse-Summary`}},
		Rule{Name: "InfluxDB", Service: "http", Ports: []int{8086},
			Header: map[string]string{"x-influxdb-version": `\d`, "x-influxdb-build": `.+`},
			Body:   []string{`"InfluxDB"`}},
		Rule{Name: "CouchDB", Service: "http", Ports: []int{5984},
			Body: []string{`"couchdb"\s*:\s*"Welcome"`, `(?i)Welcome to CouchDB`}},
		Rule{Name: "Cassandra", Service: "cassandra", Ports: []int{9042, 9160},
			Banner: []string{`(?i)cassandra`, `(?i)native protocol`}},
		Rule{Name: "Oracle TNS Listener", Service: "oracle", Ports: []int{1521, 1522},
			Banner: []string{`\(DESCRIPTION=`, `\(ERROR_STACK=`, `\(TNS-`, `\(ADDRESS=\(PROTOCOL=tcp\)`}},
		Rule{Name: "Microsoft SQL Server", Service: "mssql", Ports: []int{1433},
			Banner: []string{`(?i)microsoft sql server`, `(?i)sql server`}},
		Rule{Name: "IBM DB2", Service: "db2", Ports: []int{50000, 50001},
			Banner: []string{`(?i)db2`, `SQL30081N`, `(?i)ibm database`}},
		Rule{Name: "Neo4j", Service: "http", Ports: []int{7474, 7473},
			Header: map[string]string{"x-neo4j-version": `\d`, "x-neo4j-edition": `.+`},
			Title:  []string{`(?i)neo4j`},
			Body:   []string{`"neo4j_version"`, `(?i)neo4j`}},
		Rule{Name: "Prometheus", Service: "http", Ports: []int{9090},
			Title: []string{`(?i)prometheus`},
			Body:  []string{`Prometheus Time Series Collection`, `(?i)prometheus`}},
		Rule{Name: "OpenTSDB", Service: "http", Ports: []int{4242},
			Title: []string{`(?i)opentsdb`},
			Body:  []string{`(?i)opentsdb`}},
		Rule{Name: "QuestDB", Service: "http", Ports: []int{9000},
			Title: []string{`(?i)questdb`},
			Body:  []string{`(?i)questdb`, `/assets/questdb`}},
		Rule{Name: "TimescaleDB", Service: "postgres", Ports: []int{5432},
			Banner: []string{`(?i)timescaledb`, `PostgreSQL 1[4-9]\.\d+.*ts`}},
	)

	// ---------------- DevOps / CI / 制品库 ----------------
	out = append(out,
		Rule{Name: "SonarQube", Service: "http",
			Header: map[string]string{"x-sonarqube-version": `\d`},
			Body:   []string{`(?i)sonarqube`, `(?i)sonar\.css`}},
		Rule{Name: "Sonatype Nexus", Service: "http",
			Header: map[string]string{"server": `(?i)nexus`},
			Title:  []string{`(?i)nexus repository`},
			Body:   []string{`(?i)NXRM`, `Nexus Repository Manager`}},
		Rule{Name: "JFrog Artifactory", Service: "http",
			Header: map[string]string{"x-artifactory-id": `.+`, "x-artifactory-node-id": `.+`},
			Title:  []string{`(?i)artifactory`},
			Body:   []string{`(?i)artifactory`, `(?i)jfrog`}},
		Rule{Name: "Gitea", Service: "http",
			Header: map[string]string{"set-cookie": `i_like_gitea=`},
			Body:   []string{`(?i)gitea`, `(?i)Powered by Gitea`}},
		Rule{Name: "Gogs", Service: "http",
			Header: map[string]string{"set-cookie": `(?i)gogs`},
			Body:   []string{`(?i)Powered by Gogs`, `(?i)gogs`}},
		Rule{Name: "Drone CI", Service: "http",
			Title: []string{`(?i)drone`},
			Body:  []string{`(?i)drone`, `/drone\.js`}},
		Rule{Name: "Argo CD", Service: "http",
			Header: map[string]string{"x-argocd": `.+`},
			Title:  []string{`(?i)argo cd`},
			Body:   []string{`(?i)argocd`, `(?i)argo cd`}},
		Rule{Name: "Bitbucket", Service: "http",
			Header: map[string]string{"x-bitbucket": `.+`, "server": `(?i)bitbucket`},
			Title:  []string{`(?i)bitbucket`},
			Body:   []string{`commit-file-list`, `(?i)bitbucket`}},
		Rule{Name: "JetBrains TeamCity", Service: "http",
			Title: []string{`(?i)teamcity`},
			Body:  []string{`(?i)teamcity`}},
		Rule{Name: "Atlassian Bamboo", Service: "http",
			Title: []string{`(?i)bamboo`},
			Body:  []string{`(?i)/bamboo/`, `(?i)Atlassian Bamboo`}},
		Rule{Name: "Rundeck", Service: "http",
			Title: []string{`(?i)rundeck`},
			Body:  []string{`(?i)rundeck`}},
		Rule{Name: "Ansible AWX", Service: "http",
			Header: map[string]string{"x-awx": `.+`},
			Title:  []string{`(?i)awx`},
			Body:   []string{`(?i)awx`, `/static/awx/`}},
		Rule{Name: "Spinnaker", Service: "http",
			Title: []string{`(?i)spinnaker`},
			Body:  []string{`(?i)spinnaker`, `/spinnaker\.js`}},
	)

	// ---------------- 大数据 / 搜索 / 消息 ----------------
	out = append(out,
		// NameNode 的 Web UI 端口（Hadoop 2.x 是 50070，3.x 起是 9870）；8020 是 RPC，不认。
		Rule{Name: "Hadoop NameNode", Service: "http", Ports: []int{50070, 9870},
			Title: []string{`(?i)namenode`},
			Body:  []string{`(?i)hadoop`, `(?i)NameNode`}},
		// YARN ResourceManager 的 Web UI 是 8088；8032 是 RPC 调度端口，不列。
		Rule{Name: "Hadoop YARN ResourceManager", Service: "http", Ports: []int{8088},
			Title: []string{`(?i)resourcemanager`},
			Body:  []string{`(?i)hadoop`, `(?i)ResourceManager`}},
		Rule{Name: "Apache HiveServer2", Service: "hive", Ports: []int{10000, 10001},
			Banner: []string{`(?i)hiveserver2`, `(?i)org\.apache\.hive`}},
		// Spark Master 的 Web UI 是 8080；7077 是 RPC（spark://）端口，不列。
		Rule{Name: "Spark Master UI", Service: "http", Ports: []int{8080},
			Title: []string{`(?i)spark master`},
			Body:  []string{`(?i)spark master`, `(?i)spark://`}},
		Rule{Name: "Spark Worker UI", Service: "http", Ports: []int{8081},
			Title: []string{`(?i)spark worker`},
			Body:  []string{`(?i)spark worker`}},
		Rule{Name: "Apache Flink Dashboard", Service: "http", Ports: []int{8081, 8082},
			Title: []string{`(?i)apache flink`},
			Body:  []string{`(?i)flink`, `(?i)Flink Dashboard`}},
		Rule{Name: "Apache ZooKeeper", Service: "zookeeper", Ports: []int{2181, 2182},
			Banner: []string{`Zookeeper version:`, `^imok$`, `(?i)zookeeper`}},
		Rule{Name: "Apache ActiveMQ", Service: "http", Ports: []int{8161},
			Title: []string{`(?i)activemq`},
			Body:  []string{`(?i)activemq`}},
		Rule{Name: "RocketMQ Console", Service: "http",
			Title: []string{`(?i)rocketmq`},
			Body:  []string{`(?i)rocketmq`}},
		Rule{Name: "Apache Pulsar", Service: "http", Ports: []int{8080},
			Body: []string{`"brokerServiceUrl"\s*:`, `pulsar://`, `(?i)apache pulsar`}},
		Rule{Name: "Apache Airflow", Service: "http",
			Header: map[string]string{"set-cookie": `session=.+\.[A-Za-z0-9_\-]+\.`},
			Title:  []string{`(?i)airflow`},
			Body:   []string{`(?i)airflow`, `(?i)Airflow`}},
		Rule{Name: "Apache Superset", Service: "http",
			Title: []string{`(?i)superset`},
			Body:  []string{`(?i)superset`, `(?i)Superset`}},
		Rule{Name: "Metabase", Service: "http",
			Header: map[string]string{"x-metabase-version": `\d`},
			Title:  []string{`(?i)metabase`},
			Body:   []string{`(?i)metabase`}},
		Rule{Name: "Apache Kylin", Service: "http",
			Title: []string{`(?i)kylin`},
			Body:  []string{`(?i)kylin`}},
		Rule{Name: "Apache Doris", Service: "http", Ports: []int{8030, 8040},
			Title: []string{`(?i)doris`},
			Body:  []string{`(?i)doris`, `(?i)Doris FE`}},
		Rule{Name: "StarRocks", Service: "http", Ports: []int{8030, 8040},
			Title: []string{`(?i)starrocks`},
			Body:  []string{`(?i)starrocks`}},
	)

	// ---------------- 监控 / 日志 ----------------
	out = append(out,
		Rule{Name: "Nagios", Service: "http",
			Title: []string{`(?i)nagios`},
			Body:  []string{`(?i)nagios`, `(?i)nagioscore`}},
		Rule{Name: "Icinga", Service: "http",
			Title: []string{`(?i)icinga`},
			Body:  []string{`(?i)icinga`, `(?i)Icinga Web`}},
		Rule{Name: "Prometheus Alertmanager", Service: "http", Ports: []int{9093},
			Title: []string{`(?i)alertmanager`},
			Body:  []string{`(?i)alertmanager`, `/static/script\.js`}},
		Rule{Name: "VictoriaMetrics", Service: "http", Ports: []int{8428},
			Header: map[string]string{"x-server-hostname": `.+`},
			Title:  []string{`(?i)victoria`},
			Body:   []string{`(?i)vmui`, `(?i)victoriametrics`}},
		Rule{Name: "Netdata", Service: "http",
			Header: map[string]string{"x-netdata": `.+`},
			Title:  []string{`(?i)netdata`},
			Body:   []string{`(?i)netdata`}},
		Rule{Name: "Cacti Monitoring", Service: "http",
			Title: []string{`(?i)cacti`},
			Body:  []string{`(?i)cacti`}},
		Rule{Name: "Open-Falcon", Service: "http",
			Title: []string{`(?i)open-falcon`},
			Body:  []string{`(?i)open-falcon`, `(?i)openfalcon`}},
		Rule{Name: "Graylog", Service: "http", Ports: []int{9000, 12900},
			Header: map[string]string{"x-graylog-node-id": `.+`},
			Title:  []string{`(?i)graylog`},
			Body:   []string{`(?i)graylog`, `/assets/graylog`}},
		Rule{Name: "Grafana Loki", Service: "http", Ports: []int{3100},
			Header: map[string]string{"x-loki": `.+`},
			Body:   []string{`"status":"success"`}},
		Rule{Name: "Jaeger", Service: "http",
			Title: []string{`(?i)jaeger`},
			Body:  []string{`(?i)jaeger`, `/static/jaeger`}},
		Rule{Name: "Apache SkyWalking", Service: "http",
			Title: []string{`(?i)skywalking`},
			Body:  []string{`(?i)skywalking`, `(?i)SkyWalking`}},
		Rule{Name: "Sentinel Dashboard", Service: "http",
			Title: []string{`(?i)sentinel`},
			Body:  []string{`(?i)sentinel`, `(?i)Sentinel Dashboard`}},
		Rule{Name: "Uptime Kuma", Service: "http",
			Title: []string{`(?i)uptime kuma`},
			Body:  []string{`(?i)uptime-kuma`, `(?i)Uptime Kuma`}},
	)

	// ---------------- 代理 / 网关 / 缓存 ----------------
	out = append(out,
		Rule{Name: "HAProxy", Service: "http",
			Header: map[string]string{"server": `(?i)haproxy`},
			Title:  []string{`(?i)haproxy`},
			Body:   []string{`(?i)haproxy`}},
		Rule{Name: "Varnish", Service: "http",
			Header: map[string]string{"x-varnish": `\d+`},
			Body:   []string{`(?i)varnish`}},
		Rule{Name: "Squid", Service: "http",
			Header: map[string]string{"server": `(?i)squid`, "via": `(?i)squid`},
			Title:  []string{`(?i)squid`},
			Body:   []string{`(?i)Generated by squid`, `(?i)squid/`}},
		Rule{Name: "Traefik", Service: "http",
			Header: map[string]string{"server": `(?i)traefik`},
			Body:   []string{`(?i)traefik`, `(?i)404 page not found`}},
		Rule{Name: "Envoy", Service: "http",
			Header: map[string]string{"server": `(?i)envoy`},
			Body:   []string{`(?i)envoy`}},
		Rule{Name: "Kong Gateway", Service: "http",
			Header: map[string]string{"server": `(?i)kong`},
			Body:   []string{`(?i)kong`, `"kong"`}},
		Rule{Name: "Apache APISIX", Service: "http",
			Header: map[string]string{"server": `(?i)apisix`},
			Body:   []string{`(?i)apisix`}},
		Rule{Name: "RedisInsight", Service: "http",
			Title: []string{`(?i)redisinsight`},
			Body:  []string{`(?i)redisinsight`}},
		Rule{Name: "Redis Commander", Service: "http",
			Title: []string{`(?i)redis commander`},
			Body:  []string{`(?i)redis-commander`, `(?i)Redis Commander`}},
	)

	// ---------------- 文件 / 协作 / Web 邮件 ----------------
	out = append(out,
		Rule{Name: "Nextcloud", Service: "http",
			Header: map[string]string{"x-nextcloud": `.+`},
			Title:  []string{`(?i)nextcloud`},
			Body:   []string{`(?i)nextcloud`, `oc_sessionPassphrase`, `/core/img/actions/`}},
		Rule{Name: "ownCloud", Service: "http",
			Header: map[string]string{"x-owncloud": `.+`},
			Title:  []string{`(?i)owncloud`},
			Body:   []string{`(?i)owncloud`, `data-requesttoken=`}},
		Rule{Name: "Seafile", Service: "http",
			Title: []string{`(?i)seafile`},
			Body:  []string{`(?i)seafile`, `/media/css/seafile`}},
		Rule{Name: "Syncthing", Service: "http",
			Header: map[string]string{"x-syncthing-id": `.+`},
			Title:  []string{`(?i)syncthing`},
			Body:   []string{`(?i)syncthing`, `/syncthing/core/`}},
		Rule{Name: "Jupyter Notebook", Service: "http",
			Header: map[string]string{"set-cookie": `username-[a-z0-9]+=`},
			Body:   []string{`(?i)notebook/static/`, `(?i)"notebook"`}},
		Rule{Name: "JupyterLab", Service: "http",
			Header: map[string]string{"set-cookie": `jupyter-hub-token|_xsrf=`},
			Body:   []string{`(?i)jupyterlab`, `/lab/static/`, `(?i)"lab"`}},
		Rule{Name: "RStudio Server", Service: "http",
			Header: map[string]string{"set-cookie": `rstudio=`},
			Title:  []string{`(?i)rstudio`},
			Body:   []string{`(?i)rstudio`}},
		Rule{Name: "Kodbox", Service: "http",
			Header: map[string]string{"x-kodbox": `.+`},
			Title:  []string{`(?i)kodbox`, `(?i)可道云`},
			Body:   []string{`(?i)kodbox`, `/static/app/`}},
		Rule{Name: "ONLYOFFICE Document Server", Service: "http",
			Header: map[string]string{"x-documentserver": `.+`},
			Title:  []string{`(?i)onlyoffice`},
			Body:   []string{`(?i)onlyoffice`, `/web-apps/apps/`}},
		Rule{Name: "Roundcube Webmail", Service: "http",
			Header: map[string]string{"set-cookie": `roundcube_sessid`},
			Title:  []string{`(?i)roundcube`},
			Body:   []string{`(?i)roundcube`}},
		Rule{Name: "RainLoop Webmail", Service: "http",
			Header: map[string]string{"x-rainloop": `.+`},
			Title:  []string{`(?i)rainloop`},
			Body:   []string{`(?i)rainloop`, `name="rainloop`}},
		Rule{Name: "Zimbra Web Client", Service: "http",
			Title: []string{`(?i)zimbra`},
			Body:  []string{`(?i)zimbra`, `/zimbra/`}},
	)

	return out
}
